## Python Numpy Array Slicing(:)

In [1]:
import numpy as np

In [6]:
mx = np.arange(1,11).reshape(1,10)
print(mx)

[[ 1  2  3  4  5  6  7  8  9 10]]


In [7]:
mx[:]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [8]:
mx[:,0]

array([1])

In [10]:
mx[:,:1]

array([[1]])

In [11]:
mx[:,:1].ndim

2

In [12]:
mx[0]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
mx[:,1]

array([2])

In [14]:
mx[0,0]

np.int64(1)

In [15]:
mx[:,0:1]

array([[1]])

In [16]:
mx[1:4,1:4]

array([], shape=(0, 3), dtype=int64)

In [17]:
mx[:,1:3]

array([[2, 3]])

In [18]:
mx[:]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [19]:
mx[::]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [20]:
mx[:,:]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [21]:
mx.itemsize

8

In [22]:
mx.dtype

dtype('int64')