## MatheMetical Operation in Numpy

In [1]:
import numpy as np


In [2]:
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(1,10).reshape(3,3)
print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
arr1+arr2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [4]:
np.add(arr1,arr2)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [5]:
arr1-arr2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [8]:
arr1/arr2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
np.divide(arr1,arr2)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
arr1*arr2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [11]:
print(arr1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
np.multiply(arr1,arr2)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [14]:
arr1@arr2

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [15]:
arr1.dot(arr2)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [16]:
arr1.max()

np.int64(9)

In [17]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
arr1.argmax()

np.int64(8)

In [20]:
arr1.max(axis=0)

array([7, 8, 9])

In [21]:
arr1.max(axis=1)

array([3, 6, 9])

In [22]:
arr1.min()

np.int64(1)

In [23]:
arr1.argmin()

np.int64(0)

In [24]:
arr1.min(axis=0)

array([1, 2, 3])

In [25]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
np.sum(arr1)

np.int64(45)

In [27]:
np.sum(arr1,axis=1)

array([ 6, 15, 24])

In [28]:
np.sum(arr1,axis=0)

array([12, 15, 18])

In [29]:
np.mean(arr1)

np.float64(5.0)

In [30]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [31]:
np.std(arr1)

np.float64(2.581988897471611)

In [32]:
np.exp(arr1)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [33]:
np.log(arr1)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [34]:
np.log10(arr1)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125],
       [0.84509804, 0.90308999, 0.95424251]])