In [1]:
import numpy as np

In [2]:
arr_1d = np.array([1,2,3,4,5,6,7,8,9,0])
arr_1d

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [3]:
type(arr_1d)

numpy.ndarray

In [4]:
arr_2d = np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr_2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [5]:
arr_2d.ndim

2

In [6]:
arr_1d.size

10

In [7]:
arr_2d.size

10

In [8]:
arr_2d.shape

(2, 5)

In [10]:
arr_2d.size

10

In [12]:
arr_2d.dtype

dtype('int64')

In [13]:
mx_1s = np.array([[1,1,1],[1,1,1],[1,1,1]])
print(mx_1s)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [15]:
mx_1s = np.ones(5)
mx_1s

array([1., 1., 1., 1., 1.])

In [16]:
mx_1s.dtype

dtype('float64')

In [17]:
mx_1s = np.ones((3,4))
print(mx_1s)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [18]:
mx_1s = np.ones((3,4),dtype=int)
print(mx_1s)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [19]:
mx_ox = np.zeros((4,6))
print(mx_ox)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [20]:
mx_ox = np.zeros((4,6),dtype = bool)
print(mx_ox)

[[False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]]


In [21]:
mx_ox = np.zeros((4,6),dtype=str)
print(mx_ox)

[['' '' '' '' '' '']
 ['' '' '' '' '' '']
 ['' '' '' '' '' '']
 ['' '' '' '' '' '']]


In [22]:
em_str = ""
print(bool()