## Numpy Functions

In [1]:
import numpy as np

In [2]:
#Arrange
#np.arrange(start,ends,steps)
ar_1d = np.arange(1,13)
print(ar_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [3]:
even_array = np.arange(1,13,2)
print(even_array)

[ 1  3  5  7  9 11]


In [4]:
#linespace
np.linspace(1,5,4)

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [5]:
#reshape
ar_2d = ar_1d.reshape(2,6)
print(ar_2d)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [6]:
ar_3d = ar_1d.reshape(2,3,2)
print(ar_3d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [7]:
ar = np.arange(1,13).reshape(2,6)
print(ar)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [8]:
#ravel
ar.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [9]:
#flatten
ar.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [10]:
#transpose
ar.transpose()

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])