## Random Sampling With Numpy

In [1]:
import numpy as np
import random

In [2]:
np.random.random(1)

array([0.34243504])

In [3]:
np.random.random((3,3))

array([[0.54784702, 0.2980538 , 0.76272828],
       [0.03692524, 0.10560097, 0.09226422],
       [0.11014052, 0.67552457, 0.75659422]])

In [4]:
np.random.randint(1,4)

1

In [6]:
np.random.randint(1,4,(4,4))

array([[3, 1, 1, 2],
       [2, 3, 3, 2],
       [2, 1, 3, 3],
       [3, 2, 2, 3]], dtype=int32)

In [7]:
np.random.randint(1,4,(2,4,4))

array([[[3, 1, 1, 3],
        [1, 2, 1, 1],
        [2, 2, 1, 3],
        [1, 2, 2, 3]],

       [[1, 1, 1, 3],
        [3, 3, 1, 1],
        [2, 1, 1, 2],
        [2, 3, 1, 3]]], dtype=int32)

In [9]:
np.random.seed(10)
np.random.randint(1,4,(2,4,4))

array([[[2, 2, 1, 1],
        [2, 1, 2, 2],
        [1, 2, 2, 3],
        [1, 2, 1, 3]],

       [[1, 3, 1, 1],
        [1, 3, 1, 3],
        [3, 2, 1, 1],
        [3, 2, 3, 2]]], dtype=int32)

In [10]:
2**32-1

4294967295

In [11]:
np.random.rand(3)

array([0.13145815, 0.41366737, 0.77872881])

In [12]:
np.random.randn(3,3)

array([[-1.25424191,  0.33157855, -0.30860049],
       [-0.15373549,  0.67893119, -1.91355421],
       [-0.94245806, -1.74554298, -1.02094527]])

In [15]:
np.random.rand(3,3)

array([[0.18624777, 0.41379781, 0.23100532],
       [0.65362293, 0.76437476, 0.83487913],
       [0.21221285, 0.9619666 , 0.26114034]])

In [16]:
x = [1,2,3,4]

In [17]:
np.random.choice(x)

np.int64(3)

In [18]:
for i in range(20):
    print(np.random.choice(x))

1
2
1
1
4
4
3
2
4
2
4
2
4
3
3
4
2
2
1
1


In [19]:
np.random.permutation(x)

array([4, 1, 2, 3])